services:
  - type: web
    name: sceni-backend
    env: python
    plan: free
    buildCommand: "echo 'No build required'"
    startCommand: "python SCENI_01_NUEVO/app/main.py"
    envVars:
      - key: SCENI_DB_PATH
        value: /var/data/sceni.db
    disk:
      name: sceni-data
      mountPath: /var/data
      sizeGB: 1
